config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"
  
  #sign up route
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login route
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  #logout route
  delete '/logout' => 'sessions#destroy'

  #omniauth callback
  get "/auth/google_oauth2/callback" => 'sessions#google'

  resources :users do
    resources :lists, only: [:new,:create,:index]
  end
  resources :lists do
    resources :comments, only: [:new,:create,:index]
  end
  resources :movies
  resources :comments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :list
  belongs_to :movie

  validates :content, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :comments, :dependent => :destroy
  has_many :movies, through: :comments

  scope :alpha, -> { order(:name) }
  scope :search, ->(params) { where("(name) LIKE ?", "%#{params}%")}
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :comments, :dependent => :destroy
    has_many :lists, through: :comments

    validates :title, :rating, :release_date, :genre, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :lists
    has_many :comments

    validates :username, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    # gives access to helpers methods in my views
    helper_method :current_user, :logged_in?

    private 
    
    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!session[:user_id]
    end

    def redirect_if_not_logged_in
        redirect_to '/' if !logged_in?
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def index
        if params[:list_id] && @list = List.find_by_id(params[:list_id])
            @comments = @list.comments
        else
            @comments = Comment.all
        end
    end

    def create
        # binding.pry
        @comment = Comment.new(comment_params.merge(user_id: current_user.id))
        if @comment.save
            redirect_to list_path(id: comment_params[:list_id])
        else
            redirect_to list_path(id: comment_params[:list_id])
        end
    end
    
    def destroy
        # binding.pry
        @comment = Comment.find_by_id(params[:id])
        if @comment.destroy
            redirect_to list_path(id: @comment.list_id)
        else
            binding.pry
        end
    end
    
    private

    def comment_params
        params.require(:comment).permit(:content)
        params[:comment].permit(:list_id,:movie_id,:content)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_list, only: [:show, :edit, :update, :destroy]
     #nest under user index
     #Work on more complex scopes .where or .order
     #authentication be able to define properly
    def index
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            @lists = @user.lists.alpha
        else
           @error = "This user doesn't exist" if params[:user_id]
           @lists = List.all.alpha
        end
        if !params[:q].empty?
            @lists = List.search(params[:q].downcase)
        end
    end
    
    def new
        @list = List.new
    end
    
    def create
        @list = current_user.lists.build(list_params)
        if @list.save
            redirect_to lists_path
        else
            render :new
        end
    end

    def show
        redirect_to lists_path if !@list
        @comment = Comment.new
        @movies = Movie.all
    end

    def edit
        redirect_to lists_path if !@list || @list.user != current_user
    end
    
    def update
        redirect_to lists_path if !@list || @list.user != current_user
        if @list.update(list_params)
          redirect_to list_path(@list)
        else
          render :edit
        end
    end

    def destroy
        redirect_to lists_path if !@list || @list.user != current_user
        @list.destroy
        redirect_to lists_path
    end

    private
#set list 

    def set_list
        @list = List.find_by_id(params[:id])
    end
    def list_params
        params.require(:list).permit(:name)
    end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    
    def index
        if params[:list_id] && @list = List.find_by_id(params[:list_id])
            @movies = @list.movies
        else 
            @movies = Movie.all
        end
    end

    def new
        @movie = Movie.new
    end
    
    def create
        @movie = Movie.new(movie_params)
        if @movie.save
            redirect_to movies_path
        else
            render :new
        end
    end
    
    def show
        @movie = Movie.find_by_id(params[:id])
        redirect_to movies_path if !@movie
    end

    def edit
        @movie = Movie.find_by_id(params[:id])
        redirect_to movies_path if !@movie
    end

    def update
        @movie = Movie.find_by_id(params[:id])
        redirect_to movies_path if !@movie
        if @movie.update(movie_params)
            redirect_to movie_path(@movie)
        else
            render :edit
        end
    end

    def destroy
        # binding.pry
        @movie = Movie.find_by_id(params[:id])
        @movie.destroy
        redirect_to movies_path
    end

    private

    def movie_params
        params.require(:movie).permit(:title,:rating,:release_date,:genre,:description)
    end

    def list_movie
        List.find(params["list_id"])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def destroy
        session.clear
        redirect_to root_path
    end

    def home
        if !logged_in?
            root_path
        else
            redirect_to lists_path
        end
    end

    def create
        user = User.find_by(username: params[:user][:username])
        if user && user.authenticate(params[:user][:password])
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
            flash[:message] = "Incorrect login information"
            redirect_to "/login"
        end
    end

    def google
        #finding or creating a user using attributes
        @user = User.find_or_create_by(email: auth["info"]["email"]) do |u|
            u.username= auth["info"]["first_name"]
            u.password= SecureRandom.hex(10)
        end
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            redirect_to '/'
        end
    end

    def auth
        request.env['omniauth.auth']
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else 
            render :new
        end
    end

    def show
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h1><%= @list.name %></h1>

<% if @comments.blank? %>

    <h2>No comments yet. Write a comment <%= link_to "here", new_comment_path%></h2>

<% else %>
    <% @comments.each do |comment| %>
        <div><h5><%= link_to comment.name, comment_path(comment) %></h5></div>
    <% end %>
<% end %>

app/views/comments/new.html.erb
<h3>Movies:</h3>

<%= form_for(@comment) do |f| %> 
    
    <%= f.label :movie %>
    <%= f.collection_select :movie_id, Movie.all, :id, :title %>
  
    <%= f.label :content %>
    <%= f.text_field :content %>
  
    <%= f.submit %>
  
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this object from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">MovieList</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/lists">Movie Lists</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/lists/new">Add A Movie List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/movies/new">Add A Movie</a>
          </li>
        </ul>
      </div>
    </nav>

    <div>
      <% if logged_in? %>
      <%=link_to "Logout", logout_path, method:"delete" %> |
      <%=link_to "My Lists", user_lists_path(current_user) %> 
      <% else %>
      <%=link_to "Sign Up", signup_path %> |
      <%=link_to "Log In", login_path %> |
      <%= link_to "Log In with Google", '/auth/google_oauth2' %>
      <% end %>
    </div>

    <div>
      <%= flash[:message] if flash[:message]%>
    </div>

    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Edit <%= @list.name%>!</h1>
<%= render partial: "layouts/errors", locals: {object: @list} %>
<%= form_for(@list) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<%= form_tag("/lists", method: "get") do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
  <% end %>
<% if @lists.blank? %>

    <h2>No lists yet. Write a list <%= link_to "here", new_list_path%></h2>

<% else %>
    <% @lists.each do |list| %>
        <div><h5><%= link_to list.name, list_path(list) %></h5></div>
    <% end %>
<% end %>

app/views/lists/new.html.erb
<h1>New Movie List</h1>
<%= render partial: "layouts/errors", locals: {object: @list} %>
<%= form_for(@list) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%=@list.name%></h1>
<h5>By: <%=link_to @list.user.username, user_path(@list.user)%> </h5>

<%= render partial: "layouts/errors", locals: {object: @comment} %>

<h3>Movies:</h3>

<% @list.comments.each do |c|%>
    <li><%= c.movie.title %>: <%= c.content %><% if @list.user == current_user %> - <%= link_to "Delete", comment_path(:id => c.id), :method => :delete %></li>
<% end %>
<% end %>

<% if @list.user == current_user %>
<%= form_for(@comment) do |f| %> 
    
    <%= f.hidden_field :list_id, :value => @list.id %>
    
    <%= f.label :movie %>
    <%= f.collection_select :movie_id, Movie.all, :id, :title, {:prompt => 'Please select a Movie'} %>
  
    <%= f.label :content %>
    <%= f.text_area :content %>
  
    <%= f.submit %>
  
<% end %>


<p><%= link_to "Edit List", edit_list_path(@list)%>|<%= link_to "Delete", @list, :method => :delete %></p>
<% end %>

app/views/movies/edit.html.erb
<h1>Edit <%= @movie.title%>!</h1>
<%= render partial: "layouts/errors", locals: {object: @movie} %>

<%= form_for([@list,@movie]) do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :rating %>
    <%= f.select :rating, ['','G', 'PG', 'PG-13', 'R', 'NR']%>
    <br>
    <%= f.label :release_date %>
    <%= f.date_field :release_date %>
    <br>
    <%= f.label :genre %>
    <%= f.text_field :genre %>
    <br>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <br>
    <%= f.submit %>
<% end %>

app/views/movies/index.html.erb
<% if @movies.blank? %>

    <h2>No movies yet. Write a movie <%= link_to "here", new_movie_path%></h2>

<% else %>
    <% @movies.each do |movie| %>
        <div><h5><%= link_to movie.title , movie_path(movie) %></h5></div>
    <% end %>
<% end %>

app/views/movies/new.html.erb
<h1>Is your movie not availble to add to a list? Please add here.</h1>

<%= render partial: "layouts/errors", locals: {object: @movie} %>

<%= form_for([@list,@movie]) do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :rating %>
    <%= f.select :rating, ['','G', 'PG', 'PG-13', 'R', 'NR']%>
    <br>
    <%= f.label :release_date %>
    <%= f.date_field :release_date %>
    <br>
    <%= f.label :genre %>
    <%= f.text_field :genre %>
    <br>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <br>
    <%= f.submit %>
<% end %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<h5><%= @movie.rating %></h5>
<h5><%= @movie.release_date %></h5>
<h5><%= @movie.genre %></h5>
<h5><%= @movie.description %></h5>

<p><%= link_to "Edit movie", edit_movie_path(@movie)%>|<%= link_to "Delete", @movie, :method => :delete %></p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user, url:'/signup') do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username %>
    <br><br>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <br><br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br><br>
    <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %></h1>